import prismadb from "@/lib/prismadb";
import { auth } from "@clerk/nextjs";
import { NextResponse } from "next/server";
import { v4 as uuidv4 } from 'uuid';

export async function POST(req: Request) {
    try {
        const body = await req.json();
        const { userId } = auth();

        if (!userId) {
            return new NextResponse('Unauthorized', { status: 401 });
        }
        
        // Check if hostelId exists in the request body
        const { hostelId, ...roomData } = body;
        if (!hostelId) {
            return new NextResponse('Hostel ID is required', { status: 400 });
        }

        // Generate a unique ID for the room using UUID
        const id = uuidv4();

        const room = await prismadb.room.create({
            data: {
                ...roomData,
                hostelId,
                id, // Automatically generated by Prisma
            },
        });

        return NextResponse.json(room);
    } catch (error) {
        console.log('Error at /api/room POST', error);
        return new NextResponse('Internal Server Error', { status: 500 });
    }
}
